name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip & install maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Run Rust tests
        run: cargo test --verbose

      - name: Build & install Python extension
        run: maturin develop --release

      - name: Install Python dev requirements
        run: |
          pip install pytest numpy

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Run single-query benchmark
        run: python scripts/benchmark.py

      - name: Run batch-query benchmark
        run: python scripts/batch_benc.py

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmarks-${{ matrix.python }}
          path: |
            single_query.log
            batch_query.log
